//------------------------------------------------------------------------------
// File: JILOpTables.c                                         (c) 2005 jewe.org
//------------------------------------------------------------------------------
//
// DISCLAIMER:
// -----------
//	THIS SOFTWARE IS SUBJECT TO THE LICENSE AGREEMENT FOUND IN "jilapi.h" AND
//	"COPYING". BY USING THIS SOFTWARE YOU IMPLICITLY DECLARE YOUR AGREEMENT TO
//	THE TERMS OF THIS LICENSE.
//
// Description:
// ------------
//	Table data for JIL opcodes.
//------------------------------------------------------------------------------

#include "jilstdinc.h"

#include "jiltypes.h"
#include "jilopcodes.h"

//------------------------------------------------------------------------------
// Instruction size table
//------------------------------------------------------------------------------

const JILLong JILInstructionSize[JILNumOpcodes] = {
	1,	// nop
	3,	// alloc
	4,	// alloca
	3,	// allocn
	2,	// bra
	1,	// brk
	3,	// callm
	2,	// calls
	3,	// calln
	3,	// cvf
	3,	// cvl
	2,	// popm
	3,	// popr
	2,	// pushm
	3,	// pushr
	1,	// ret
	3,	// size
	3,	// type
	2,	// dec_r
	3,	// dec_d
	3,	// dec_x
	2,	// dec_s
	2,	// inc_r
	3,	// inc_d
	3,	// inc_x
	2,	// inc_s
	3,	// moveh_r
	4,	// moveh_d
	4,	// moveh_x
	3,	// moveh_s
	2,	// neg_r
	3,	// neg_d
	3,	// neg_x
	2,	// neg_s
	2,	// not_r
	3,	// not_d
	3,	// not_x
	2,	// not_s
	3,	// tsteq_r
	4,	// tsteq_d
	4,	// tsteq_x
	3,	// tsteq_s
	3,	// tstne_r
	4,	// tstne_d
	4,	// tstne_x
	3,	// tstne_s
	3,	// add_rr
	4,	// add_rd
	4,	// add_rx
	3,	// add_rs
	4,	// add_dr
	4,	// add_xr
	3,	// add_sr
	3,	// and_rr
	4,	// and_rd
	4,	// and_rx
	3,	// and_rs
	4,	// and_dr
	4,	// and_xr
	3,	// and_sr
	3,	// asl_rr
	4,	// asl_rd
	4,	// asl_rx
	3,	// asl_rs
	4,	// asl_dr
	4,	// asl_xr
	3,	// asl_sr
	3,	// asr_rr
	4,	// asr_rd
	4,	// asr_rx
	3,	// asr_rs
	4,	// asr_dr
	4,	// asr_xr
	3,	// asr_sr
	3,	// div_rr
	4,	// div_rd
	4,	// div_rx
	3,	// div_rs
	4,	// div_dr
	4,	// div_xr
	3,	// div_sr
	3,	// lsl_rr
	4,	// lsl_rd
	4,	// lsl_rx
	3,	// lsl_rs
	4,	// lsl_dr
	4,	// lsl_xr
	3,	// lsl_sr
	3,	// lsr_rr
	4,	// lsr_rd
	4,	// lsr_rx
	3,	// lsr_rs
	4,	// lsr_dr
	4,	// lsr_xr
	3,	// lsr_sr
	3,	// mod_rr
	4,	// mod_rd
	4,	// mod_rx
	3,	// mod_rs
	4,	// mod_dr
	4,	// mod_xr
	3,	// mod_sr
	3,	// mul_rr
	4,	// mul_rd
	4,	// mul_rx
	3,	// mul_rs
	4,	// mul_dr
	4,	// mul_xr
	3,	// mul_sr
	3,	// or_rr
	4,	// or_rd
	4,	// or_rx
	3,	// or_rs
	4,	// or_dr
	4,	// or_xr
	3,	// or_sr
	3,	// sub_rr
	4,	// sub_rd
	4,	// sub_rx
	3,	// sub_rs
	4,	// sub_dr
	4,	// sub_xr
	3,	// sub_sr
	3,	// xor_rr
	4,	// xor_rd
	4,	// xor_rx
	3,	// xor_rs
	4,	// xor_dr
	4,	// xor_xr
	3,	// xor_sr
	3,	// move_rr
	4,	// move_rd
	4,	// move_rx
	3,	// move_rs
	4,	// move_dr
	5,	// move_dd
	5,	// move_dx
	4,	// move_ds
	4,	// move_xr
	5,	// move_xd
	5,	// move_xx
	4,	// move_xs
	3,	// move_sr
	4,	// move_sd
	4,	// move_sx
	3,	// move_ss

	// extensions 2004/10/30
	2,	// ldz_r

	// extensions 2004/11/10
	3,	// copy_rr
	4,	// copy_rd
	4,	// copy_rx
	3,	// copy_rs
	4,	// copy_dr
	5,	// copy_dd
	5,	// copy_dx
	4,	// copy_ds
	4,	// copy_xr
	5,	// copy_xd
	5,	// copy_xx
	4,	// copy_xs
	3,	// copy_sr
	4,	// copy_sd
	4,	// copy_sx
	3,	// copy_ss
	2,	// pop_r
	3,	// pop_d
	3,	// pop_x
	2,	// pop_s
	2,	// push_r
	3,	// push_d
	3,	// push_x
	2,	// push_s

	// extensions 2004/11/28
	3,	// copyh_r
	4,	// copyh_d
	4,	// copyh_x
	3,	// copyh_s
	4,	// cseq_rr
	5,	// cseq_rd
	5,	// cseq_rx
	4,	// cseq_rs
	5,	// cseq_dr
	5,	// cseq_xr
	4,	// cseq_sr
	4,	// csne_rr
	5,	// csne_rd
	5,	// csne_rx
	4,	// csne_rs
	5,	// csne_dr
	5,	// csne_xr
	4,	// csne_sr
	4,	// csgt_rr
	5,	// csgt_rd
	5,	// csgt_rx
	4,	// csgt_rs
	5,	// csgt_dr
	5,	// csgt_xr
	4,	// csgt_sr
	4,	// csge_rr
	5,	// csge_rd
	5,	// csge_rx
	4,	// csge_rs
	5,	// csge_dr
	5,	// csge_xr
	4,	// csge_sr
	4,	// cslt_rr
	5,	// cslt_rd
	5,	// cslt_rx
	4,	// cslt_rs
	5,	// cslt_dr
	5,	// cslt_xr
	4,	// cslt_sr
	4,	// csle_rr
	5,	// csle_rd
	5,	// csle_rx
	4,	// csle_rs
	5,	// csle_dr
	5,	// csle_xr
	4,	// csle_sr

	// extensions 2004/12/06
	3,	// snul_rr
	3,	// snnul_rr
	2,	// unot_r
	3,	// unot_d
	3,	// unot_x
	2,	// unot_s

	// extensions 2004/12/16
	4,	// streq_rr
	5,	// streq_rd
	5,	// streq_rx
	4,	// streq_rs
	5,	// streq_dr
	5,	// streq_xr
	4,	// streq_sr
	4,	// strne_rr
	5,	// strne_rd
	5,	// strne_rx
	4,	// strne_rs
	5,	// strne_dr
	5,	// strne_xr
	4,	// strne_sr
	3,	// stradd_rr
	4,	// stradd_rd
	4,	// stradd_rx
	3,	// stradd_rs
	4,	// stradd_dr
	4,	// stradd_xr
	3,	// stradd_sr
	3,	// arrcp_rr
	4,	// arrcp_rd
	4,	// arrcp_rx
	3,	// arrcp_rs
	4,	// arrcp_dr
	4,	// arrcp_xr
	3,	// arrcp_sr
	3,	// arrmv_rr
	4,	// arrmv_rd
	4,	// arrmv_rx
	3,	// arrmv_rs
	4,	// arrmv_dr
	4,	// arrmv_xr
	3,	// arrmv_sr

	// extensions 2005/02/19 defined in jiloparith.c
	3,	// addl_rr
	4,	// addl_rd
	4,	// addl_rx
	3,	// addl_rs
	4,	// addl_dr
	4,	// addl_xr
	3,	// addl_sr
	3,	// subl_rr
	4,	// subl_rd
	4,	// subl_rx
	3,	// subl_rs
	4,	// subl_dr
	4,	// subl_xr
	3,	// subl_sr
	3,	// mull_rr
	4,	// mull_rd
	4,	// mull_rx
	3,	// mull_rs
	4,	// mull_dr
	4,	// mull_xr
	3,	// mull_sr
	3,	// divl_rr
	4,	// divl_rd
	4,	// divl_rx
	3,	// divl_rs
	4,	// divl_dr
	4,	// divl_xr
	3,	// divl_sr
	3,	// modl_rr
	4,	// modl_rd
	4,	// modl_rx
	3,	// modl_rs
	4,	// modl_dr
	4,	// modl_xr
	3,	// modl_sr
	2,	// decl_r
	3,	// decl_d
	3,	// decl_x
	2,	// decl_s
	2,	// incl_r
	3,	// incl_d
	3,	// incl_x
	2,	// incl_s
	2,	// negl_r
	3,	// negl_d
	3,	// negl_x
	2,	// negl_s
	4,	// cseql_rr
	5,	// cseql_rd
	5,	// cseql_rx
	4,	// cseql_rs
	5,	// cseql_dr
	5,	// cseql_xr
	4,	// cseql_sr
	4,	// csnel_rr
	5,	// csnel_rd
	5,	// csnel_rx
	4,	// csnel_rs
	5,	// csnel_dr
	5,	// csnel_xr
	4,	// csnel_sr
	4,	// csgtl_rr
	5,	// csgtl_rd
	5,	// csgtl_rx
	4,	// csgtl_rs
	5,	// csgtl_dr
	5,	// csgtl_xr
	4,	// csgtl_sr
	4,	// csgel_rr
	5,	// csgel_rd
	5,	// csgel_rx
	4,	// csgel_rs
	5,	// csgel_dr
	5,	// csgel_xr
	4,	// csgel_sr
	4,	// csltl_rr
	5,	// csltl_rd
	5,	// csltl_rx
	4,	// csltl_rs
	5,	// csltl_dr
	5,	// csltl_xr
	4,	// csltl_sr
	4,	// cslel_rr
	5,	// cslel_rd
	5,	// cslel_rx
	4,	// cslel_rs
	5,	// cslel_dr
	5,	// cslel_xr
	4,	// cslel_sr

	3,	// addf_rr
	4,	// addf_rd
	4,	// addf_rx
	3,	// addf_rs
	4,	// addf_dr
	4,	// addf_xr
	3,	// addf_sr
	3,	// subf_rr
	4,	// subf_rd
	4,	// subf_rx
	3,	// subf_rs
	4,	// subf_dr
	4,	// subf_xr
	3,	// subf_sr
	3,	// mulf_rr
	4,	// mulf_rd
	4,	// mulf_rx
	3,	// mulf_rs
	4,	// mulf_dr
	4,	// mulf_xr
	3,	// mulf_sr
	3,	// divf_rr
	4,	// divf_rd
	4,	// divf_rx
	3,	// divf_rs
	4,	// divf_dr
	4,	// divf_xr
	3,	// divf_sr
	3,	// modf_rr
	4,	// modf_rd
	4,	// modf_rx
	3,	// modf_rs
	4,	// modf_dr
	4,	// modf_xr
	3,	// modf_sr
	2,	// decf_r
	3,	// decf_d
	3,	// decf_x
	2,	// decf_s
	2,	// incf_r
	3,	// incf_d
	3,	// incf_x
	2,	// incf_s
	2,	// negf_r
	3,	// negf_d
	3,	// negf_x
	2,	// negf_s
	4,	// cseqf_rr
	5,	// cseqf_rd
	5,	// cseqf_rx
	4,	// cseqf_rs
	5,	// cseqf_dr
	5,	// cseqf_xr
	4,	// cseqf_sr
	4,	// csnef_rr
	5,	// csnef_rd
	5,	// csnef_rx
	4,	// csnef_rs
	5,	// csnef_dr
	5,	// csnef_xr
	4,	// csnef_sr
	4,	// csgtf_rr
	5,	// csgtf_rd
	5,	// csgtf_rx
	4,	// csgtf_rs
	5,	// csgtf_dr
	5,	// csgtf_xr
	4,	// csgtf_sr
	4,	// csgef_rr
	5,	// csgef_rd
	5,	// csgef_rx
	4,	// csgef_rs
	5,	// csgef_dr
	5,	// csgef_xr
	4,	// csgef_sr
	4,	// csltf_rr
	5,	// csltf_rd
	5,	// csltf_rx
	4,	// csltf_rs
	5,	// csltf_dr
	5,	// csltf_xr
	4,	// csltf_sr
	4,	// cslef_rr
	5,	// cslef_rd
	5,	// cslef_rx
	4,	// cslef_rs
	5,	// cslef_dr
	5,	// cslef_xr
	4,	// cslef_sr

	// extensions 2005-03-28
	1,	// pop
	1,	// push

	// extensions 2005-11-12
	3,	// rtchk_r
	4,	// rtchk_d
	4,	// rtchk_x
	3,	// rtchk_s

	// extensions 2005-11-25
	2,	// op_jsr
	2,	// op_jsr_r
	3,	// op_jsr_d
	3,	// op_jsr_x
	2,	// op_jsr_s

	// extensions 2006-07-01
	5,	// op_newctx
	2,	// op_resume_r
	3,	// op_resume_d
	3,	// op_resume_x
	2,	// op_resume_s
	1,	// op_yield

	// extensions 2006-07-12, "weak references"
	3,	// op_wref_rr
	4,	// op_wref_rd
	4,	// op_wref_rx
	3,	// op_wref_rs
	4,	// op_wref_dr
	5,	// op_wref_dd
	5,	// op_wref_dx
	4,	// op_wref_ds
	4,	// op_wref_xr
	5,	// op_wref_xd
	5,	// op_wref_xx
	4,	// op_wref_xs
	3,	// op_wref_sr
	4,	// op_wref_sd
	4,	// op_wref_sx
	3,	// op_wref_ss

	// extensions 2007-09-13
	4,	// op_cmpref_rr

	// extensions 2008-04-13
	4,	// op_newdg
	5,	// op_newdgm
	2,	// op_calldg_r
	3,	// op_calldg_d
	3,	// op_calldg_x
	2,	// op_calldg_s

	// extensions 2010-02-15
	1,	// op_throw

	// extensions 2014-04-12
	3,	// op_alloci
	3	// op_calli
};
