//------------------------------------------------------------------------------
// File: JILOpTables.c                                         (c) 2005 jewe.org
//------------------------------------------------------------------------------
//
// DISCLAIMER:
// -----------
//  THIS SOFTWARE IS SUBJECT TO THE LICENSE AGREEMENT FOUND IN "jilapi.h" AND
//  "COPYING". BY USING THIS SOFTWARE YOU IMPLICITLY DECLARE YOUR AGREEMENT TO
//  THE TERMS OF THIS LICENSE.
//
// Description:
// ------------
//  Table data for JIL opcodes.
//------------------------------------------------------------------------------

#include "jilstdinc.h"

#include "jiltypes.h"
#include "jilopcodes.h"

//------------------------------------------------------------------------------
// g_InstructionInfo
//------------------------------------------------------------------------------
// This is the instruction table, defining an instruction info record for every
// opcode the virtual machine supports.

const JILInstrInfo g_InstructionInfo[JILNumOpcodes] =
{
	op_nop,         1, 0,   ot_none,    ot_none,    ot_none,    ot_none,    "nop",
	op_alloc,       3, 2,   ot_type,    ot_ear,     ot_none,    ot_none,    "alloc",
	op_alloca,      4, 3,   ot_type,    ot_number,  ot_ear,     ot_none,    "alloca",
	op_allocn,      3, 2,   ot_type,    ot_ear,     ot_none,    ot_none,    "allocn",
	op_bra,         2, 1,   ot_label,   ot_none,    ot_none,    ot_none,    "bra",
	op_brk,         1, 0,   ot_none,    ot_none,    ot_none,    ot_none,    "brk",
	op_callm,       3, 2,   ot_type,    ot_number,  ot_none,    ot_none,    "callm",
	op_calls,       2, 1,   ot_number,  ot_none,    ot_none,    ot_none,    "calls",
	op_calln,       3, 2,   ot_type,    ot_number,  ot_none,    ot_none,    "calln",
	op_cvf,         3, 2,   ot_ear,     ot_ear,     ot_none,    ot_none,    "cvf",
	op_cvl,         3, 2,   ot_ear,     ot_ear,     ot_none,    ot_none,    "cvl",
	op_popm,        2, 1,   ot_number,  ot_none,    ot_none,    ot_none,    "popm",
	op_popr,        3, 1,   ot_regrng,  ot_none,    ot_none,    ot_none,    "popr",
	op_pushm,       2, 1,   ot_number,  ot_none,    ot_none,    ot_none,    "pushm",
	op_pushr,       3, 1,   ot_regrng,  ot_none,    ot_none,    ot_none,    "pushr",
	op_ret,         1, 0,   ot_none,    ot_none,    ot_none,    ot_none,    "ret",
	op_size,        3, 2,   ot_ear,     ot_ear,     ot_none,    ot_none,    "size",
	op_type,        3, 2,   ot_ear,     ot_ear,     ot_none,    ot_none,    "type",
	op_dec_r,       2, 1,   ot_ear,     ot_none,    ot_none,    ot_none,    "dec",
	op_dec_d,       3, 1,   ot_ead,     ot_none,    ot_none,    ot_none,    "dec",
	op_dec_x,       3, 1,   ot_eax,     ot_none,    ot_none,    ot_none,    "dec",
	op_dec_s,       2, 1,   ot_eas,     ot_none,    ot_none,    ot_none,    "dec",
	op_inc_r,       2, 1,   ot_ear,     ot_none,    ot_none,    ot_none,    "inc",
	op_inc_d,       3, 1,   ot_ead,     ot_none,    ot_none,    ot_none,    "inc",
	op_inc_x,       3, 1,   ot_eax,     ot_none,    ot_none,    ot_none,    "inc",
	op_inc_s,       2, 1,   ot_eas,     ot_none,    ot_none,    ot_none,    "inc",
	op_moveh_r,     3, 2,   ot_handle,  ot_ear,     ot_none,    ot_none,    "moveh",
	op_moveh_d,     4, 2,   ot_handle,  ot_ead,     ot_none,    ot_none,    "moveh",
	op_moveh_x,     4, 2,   ot_handle,  ot_eax,     ot_none,    ot_none,    "moveh",
	op_moveh_s,     3, 2,   ot_handle,  ot_eas,     ot_none,    ot_none,    "moveh",
	op_neg_r,       2, 1,   ot_ear,     ot_none,    ot_none,    ot_none,    "neg",
	op_neg_d,       3, 1,   ot_ead,     ot_none,    ot_none,    ot_none,    "neg",
	op_neg_x,       3, 1,   ot_eax,     ot_none,    ot_none,    ot_none,    "neg",
	op_neg_s,       2, 1,   ot_eas,     ot_none,    ot_none,    ot_none,    "neg",
	op_not_r,       2, 1,   ot_ear,     ot_none,    ot_none,    ot_none,    "not",
	op_not_d,       3, 1,   ot_ead,     ot_none,    ot_none,    ot_none,    "not",
	op_not_x,       3, 1,   ot_eax,     ot_none,    ot_none,    ot_none,    "not",
	op_not_s,       2, 1,   ot_eas,     ot_none,    ot_none,    ot_none,    "not",
	op_tsteq_r,     3, 2,   ot_ear,     ot_label,   ot_none,    ot_none,    "tsteq",
	op_tsteq_d,     4, 2,   ot_ead,     ot_label,   ot_none,    ot_none,    "tsteq",
	op_tsteq_x,     4, 2,   ot_eax,     ot_label,   ot_none,    ot_none,    "tsteq",
	op_tsteq_s,     3, 2,   ot_eas,     ot_label,   ot_none,    ot_none,    "tsteq",
	op_tstne_r,     3, 2,   ot_ear,     ot_label,   ot_none,    ot_none,    "tstne",
	op_tstne_d,     4, 2,   ot_ead,     ot_label,   ot_none,    ot_none,    "tstne",
	op_tstne_x,     4, 2,   ot_eax,     ot_label,   ot_none,    ot_none,    "tstne",
	op_tstne_s,     3, 2,   ot_eas,     ot_label,   ot_none,    ot_none,    "tstne",
	op_add_rr,      3, 2,   ot_ear,     ot_ear,     ot_none,    ot_none,    "add",
	op_add_rd,      4, 2,   ot_ear,     ot_ead,     ot_none,    ot_none,    "add",
	op_add_rx,      4, 2,   ot_ear,     ot_eax,     ot_none,    ot_none,    "add",
	op_add_rs,      3, 2,   ot_ear,     ot_eas,     ot_none,    ot_none,    "add",
	op_add_dr,      4, 2,   ot_ead,     ot_ear,     ot_none,    ot_none,    "add",
	op_add_xr,      4, 2,   ot_eax,     ot_ear,     ot_none,    ot_none,    "add",
	op_add_sr,      3, 2,   ot_eas,     ot_ear,     ot_none,    ot_none,    "add",
	op_and_rr,      3, 2,   ot_ear,     ot_ear,     ot_none,    ot_none,    "and",
	op_and_rd,      4, 2,   ot_ear,     ot_ead,     ot_none,    ot_none,    "and",
	op_and_rx,      4, 2,   ot_ear,     ot_eax,     ot_none,    ot_none,    "and",
	op_and_rs,      3, 2,   ot_ear,     ot_eas,     ot_none,    ot_none,    "and",
	op_and_dr,      4, 2,   ot_ead,     ot_ear,     ot_none,    ot_none,    "and",
	op_and_xr,      4, 2,   ot_eax,     ot_ear,     ot_none,    ot_none,    "and",
	op_and_sr,      3, 2,   ot_eas,     ot_ear,     ot_none,    ot_none,    "and",
	op_asl_rr,      3, 2,   ot_ear,     ot_ear,     ot_none,    ot_none,    "asl",
	op_asl_rd,      4, 2,   ot_ear,     ot_ead,     ot_none,    ot_none,    "asl",
	op_asl_rx,      4, 2,   ot_ear,     ot_eax,     ot_none,    ot_none,    "asl",
	op_asl_rs,      3, 2,   ot_ear,     ot_eas,     ot_none,    ot_none,    "asl",
	op_asl_dr,      4, 2,   ot_ead,     ot_ear,     ot_none,    ot_none,    "asl",
	op_asl_xr,      4, 2,   ot_eax,     ot_ear,     ot_none,    ot_none,    "asl",
	op_asl_sr,      3, 2,   ot_eas,     ot_ear,     ot_none,    ot_none,    "asl",
	op_asr_rr,      3, 2,   ot_ear,     ot_ear,     ot_none,    ot_none,    "asr",
	op_asr_rd,      4, 2,   ot_ear,     ot_ead,     ot_none,    ot_none,    "asr",
	op_asr_rx,      4, 2,   ot_ear,     ot_eax,     ot_none,    ot_none,    "asr",
	op_asr_rs,      3, 2,   ot_ear,     ot_eas,     ot_none,    ot_none,    "asr",
	op_asr_dr,      4, 2,   ot_ead,     ot_ear,     ot_none,    ot_none,    "asr",
	op_asr_xr,      4, 2,   ot_eax,     ot_ear,     ot_none,    ot_none,    "asr",
	op_asr_sr,      3, 2,   ot_eas,     ot_ear,     ot_none,    ot_none,    "asr",
	op_div_rr,      3, 2,   ot_ear,     ot_ear,     ot_none,    ot_none,    "div",
	op_div_rd,      4, 2,   ot_ear,     ot_ead,     ot_none,    ot_none,    "div",
	op_div_rx,      4, 2,   ot_ear,     ot_eax,     ot_none,    ot_none,    "div",
	op_div_rs,      3, 2,   ot_ear,     ot_eas,     ot_none,    ot_none,    "div",
	op_div_dr,      4, 2,   ot_ead,     ot_ear,     ot_none,    ot_none,    "div",
	op_div_xr,      4, 2,   ot_eax,     ot_ear,     ot_none,    ot_none,    "div",
	op_div_sr,      3, 2,   ot_eas,     ot_ear,     ot_none,    ot_none,    "div",
	op_lsl_rr,      3, 2,   ot_ear,     ot_ear,     ot_none,    ot_none,    "lsl",
	op_lsl_rd,      4, 2,   ot_ear,     ot_ead,     ot_none,    ot_none,    "lsl",
	op_lsl_rx,      4, 2,   ot_ear,     ot_eax,     ot_none,    ot_none,    "lsl",
	op_lsl_rs,      3, 2,   ot_ear,     ot_eas,     ot_none,    ot_none,    "lsl",
	op_lsl_dr,      4, 2,   ot_ead,     ot_ear,     ot_none,    ot_none,    "lsl",
	op_lsl_xr,      4, 2,   ot_eax,     ot_ear,     ot_none,    ot_none,    "lsl",
	op_lsl_sr,      3, 2,   ot_eas,     ot_ear,     ot_none,    ot_none,    "lsl",
	op_lsr_rr,      3, 2,   ot_ear,     ot_ear,     ot_none,    ot_none,    "lsr",
	op_lsr_rd,      4, 2,   ot_ear,     ot_ead,     ot_none,    ot_none,    "lsr",
	op_lsr_rx,      4, 2,   ot_ear,     ot_eax,     ot_none,    ot_none,    "lsr",
	op_lsr_rs,      3, 2,   ot_ear,     ot_eas,     ot_none,    ot_none,    "lsr",
	op_lsr_dr,      4, 2,   ot_ead,     ot_ear,     ot_none,    ot_none,    "lsr",
	op_lsr_xr,      4, 2,   ot_eax,     ot_ear,     ot_none,    ot_none,    "lsr",
	op_lsr_sr,      3, 2,   ot_eas,     ot_ear,     ot_none,    ot_none,    "lsr",
	op_mod_rr,      3, 2,   ot_ear,     ot_ear,     ot_none,    ot_none,    "mod",
	op_mod_rd,      4, 2,   ot_ear,     ot_ead,     ot_none,    ot_none,    "mod",
	op_mod_rx,      4, 2,   ot_ear,     ot_eax,     ot_none,    ot_none,    "mod",
	op_mod_rs,      3, 2,   ot_ear,     ot_eas,     ot_none,    ot_none,    "mod",
	op_mod_dr,      4, 2,   ot_ead,     ot_ear,     ot_none,    ot_none,    "mod",
	op_mod_xr,      4, 2,   ot_eax,     ot_ear,     ot_none,    ot_none,    "mod",
	op_mod_sr,      3, 2,   ot_eas,     ot_ear,     ot_none,    ot_none,    "mod",
	op_mul_rr,      3, 2,   ot_ear,     ot_ear,     ot_none,    ot_none,    "mul",
	op_mul_rd,      4, 2,   ot_ear,     ot_ead,     ot_none,    ot_none,    "mul",
	op_mul_rx,      4, 2,   ot_ear,     ot_eax,     ot_none,    ot_none,    "mul",
	op_mul_rs,      3, 2,   ot_ear,     ot_eas,     ot_none,    ot_none,    "mul",
	op_mul_dr,      4, 2,   ot_ead,     ot_ear,     ot_none,    ot_none,    "mul",
	op_mul_xr,      4, 2,   ot_eax,     ot_ear,     ot_none,    ot_none,    "mul",
	op_mul_sr,      3, 2,   ot_eas,     ot_ear,     ot_none,    ot_none,    "mul",
	op_or_rr,       3, 2,   ot_ear,     ot_ear,     ot_none,    ot_none,    "or",
	op_or_rd,       4, 2,   ot_ear,     ot_ead,     ot_none,    ot_none,    "or",
	op_or_rx,       4, 2,   ot_ear,     ot_eax,     ot_none,    ot_none,    "or",
	op_or_rs,       3, 2,   ot_ear,     ot_eas,     ot_none,    ot_none,    "or",
	op_or_dr,       4, 2,   ot_ead,     ot_ear,     ot_none,    ot_none,    "or",
	op_or_xr,       4, 2,   ot_eax,     ot_ear,     ot_none,    ot_none,    "or",
	op_or_sr,       3, 2,   ot_eas,     ot_ear,     ot_none,    ot_none,    "or",
	op_sub_rr,      3, 2,   ot_ear,     ot_ear,     ot_none,    ot_none,    "sub",
	op_sub_rd,      4, 2,   ot_ear,     ot_ead,     ot_none,    ot_none,    "sub",
	op_sub_rx,      4, 2,   ot_ear,     ot_eax,     ot_none,    ot_none,    "sub",
	op_sub_rs,      3, 2,   ot_ear,     ot_eas,     ot_none,    ot_none,    "sub",
	op_sub_dr,      4, 2,   ot_ead,     ot_ear,     ot_none,    ot_none,    "sub",
	op_sub_xr,      4, 2,   ot_eax,     ot_ear,     ot_none,    ot_none,    "sub",
	op_sub_sr,      3, 2,   ot_eas,     ot_ear,     ot_none,    ot_none,    "sub",
	op_xor_rr,      3, 2,   ot_ear,     ot_ear,     ot_none,    ot_none,    "xor",
	op_xor_rd,      4, 2,   ot_ear,     ot_ead,     ot_none,    ot_none,    "xor",
	op_xor_rx,      4, 2,   ot_ear,     ot_eax,     ot_none,    ot_none,    "xor",
	op_xor_rs,      3, 2,   ot_ear,     ot_eas,     ot_none,    ot_none,    "xor",
	op_xor_dr,      4, 2,   ot_ead,     ot_ear,     ot_none,    ot_none,    "xor",
	op_xor_xr,      4, 2,   ot_eax,     ot_ear,     ot_none,    ot_none,    "xor",
	op_xor_sr,      3, 2,   ot_eas,     ot_ear,     ot_none,    ot_none,    "xor",
	op_move_rr,     3, 2,   ot_ear,     ot_ear,     ot_none,    ot_none,    "move",
	op_move_rd,     4, 2,   ot_ear,     ot_ead,     ot_none,    ot_none,    "move",
	op_move_rx,     4, 2,   ot_ear,     ot_eax,     ot_none,    ot_none,    "move",
	op_move_rs,     3, 2,   ot_ear,     ot_eas,     ot_none,    ot_none,    "move",
	op_move_dr,     4, 2,   ot_ead,     ot_ear,     ot_none,    ot_none,    "move",
	op_move_dd,     5, 2,   ot_ead,     ot_ead,     ot_none,    ot_none,    "move",
	op_move_dx,     5, 2,   ot_ead,     ot_eax,     ot_none,    ot_none,    "move",
	op_move_ds,     4, 2,   ot_ead,     ot_eas,     ot_none,    ot_none,    "move",
	op_move_xr,     4, 2,   ot_eax,     ot_ear,     ot_none,    ot_none,    "move",
	op_move_xd,     5, 2,   ot_eax,     ot_ead,     ot_none,    ot_none,    "move",
	op_move_xx,     5, 2,   ot_eax,     ot_eax,     ot_none,    ot_none,    "move",
	op_move_xs,     4, 2,   ot_eax,     ot_eas,     ot_none,    ot_none,    "move",
	op_move_sr,     3, 2,   ot_eas,     ot_ear,     ot_none,    ot_none,    "move",
	op_move_sd,     4, 2,   ot_eas,     ot_ead,     ot_none,    ot_none,    "move",
	op_move_sx,     4, 2,   ot_eas,     ot_eax,     ot_none,    ot_none,    "move",
	op_move_ss,     3, 2,   ot_eas,     ot_eas,     ot_none,    ot_none,    "move",

	// extensions 2004/10/30
	op_ldz_r,       2, 1,   ot_ear,     ot_none,    ot_none,    ot_none,    "ldz",

	// extensions 2004/11/10
	op_copy_rr,     3, 2,   ot_ear,     ot_ear,     ot_none,    ot_none,    "copy",
	op_copy_rd,     4, 2,   ot_ear,     ot_ead,     ot_none,    ot_none,    "copy",
	op_copy_rx,     4, 2,   ot_ear,     ot_eax,     ot_none,    ot_none,    "copy",
	op_copy_rs,     3, 2,   ot_ear,     ot_eas,     ot_none,    ot_none,    "copy",
	op_copy_dr,     4, 2,   ot_ead,     ot_ear,     ot_none,    ot_none,    "copy",
	op_copy_dd,     5, 2,   ot_ead,     ot_ead,     ot_none,    ot_none,    "copy",
	op_copy_dx,     5, 2,   ot_ead,     ot_eax,     ot_none,    ot_none,    "copy",
	op_copy_ds,     4, 2,   ot_ead,     ot_eas,     ot_none,    ot_none,    "copy",
	op_copy_xr,     4, 2,   ot_eax,     ot_ear,     ot_none,    ot_none,    "copy",
	op_copy_xd,     5, 2,   ot_eax,     ot_ead,     ot_none,    ot_none,    "copy",
	op_copy_xx,     5, 2,   ot_eax,     ot_eax,     ot_none,    ot_none,    "copy",
	op_copy_xs,     4, 2,   ot_eax,     ot_eas,     ot_none,    ot_none,    "copy",
	op_copy_sr,     3, 2,   ot_eas,     ot_ear,     ot_none,    ot_none,    "copy",
	op_copy_sd,     4, 2,   ot_eas,     ot_ead,     ot_none,    ot_none,    "copy",
	op_copy_sx,     4, 2,   ot_eas,     ot_eax,     ot_none,    ot_none,    "copy",
	op_copy_ss,     3, 2,   ot_eas,     ot_eas,     ot_none,    ot_none,    "copy",
	op_pop_r,       2, 1,   ot_ear,     ot_none,    ot_none,    ot_none,    "pop",
	op_pop_d,       3, 1,   ot_ead,     ot_none,    ot_none,    ot_none,    "pop",
	op_pop_x,       3, 1,   ot_eax,     ot_none,    ot_none,    ot_none,    "pop",
	op_pop_s,       2, 1,   ot_eas,     ot_none,    ot_none,    ot_none,    "pop",
	op_push_r,      2, 1,   ot_ear,     ot_none,    ot_none,    ot_none,    "push",
	op_push_d,      3, 1,   ot_ead,     ot_none,    ot_none,    ot_none,    "push",
	op_push_x,      3, 1,   ot_eax,     ot_none,    ot_none,    ot_none,    "push",
	op_push_s,      2, 1,   ot_eas,     ot_none,    ot_none,    ot_none,    "push",

	// extensions 2004/11/28
	op_copyh_r,     3, 2,   ot_handle,  ot_ear,     ot_none,    ot_none,    "copyh",
	op_copyh_d,     4, 2,   ot_handle,  ot_ead,     ot_none,    ot_none,    "copyh",
	op_copyh_x,     4, 2,   ot_handle,  ot_eax,     ot_none,    ot_none,    "copyh",
	op_copyh_s,     3, 2,   ot_handle,  ot_eas,     ot_none,    ot_none,    "copyh",
	op_cseq_rr,     4, 3,   ot_ear,     ot_ear,     ot_ear,     ot_none,    "cseq",
	op_cseq_rd,     5, 3,   ot_ear,     ot_ead,     ot_ear,     ot_none,    "cseq",
	op_cseq_rx,     5, 3,   ot_ear,     ot_eax,     ot_ear,     ot_none,    "cseq",
	op_cseq_rs,     4, 3,   ot_ear,     ot_eas,     ot_ear,     ot_none,    "cseq",
	op_cseq_dr,     5, 3,   ot_ead,     ot_ear,     ot_ear,     ot_none,    "cseq",
	op_cseq_xr,     5, 3,   ot_eax,     ot_ear,     ot_ear,     ot_none,    "cseq",
	op_cseq_sr,     4, 3,   ot_eas,     ot_ear,     ot_ear,     ot_none,    "cseq",
	op_csne_rr,     4, 3,   ot_ear,     ot_ear,     ot_ear,     ot_none,    "csne",
	op_csne_rd,     5, 3,   ot_ear,     ot_ead,     ot_ear,     ot_none,    "csne",
	op_csne_rx,     5, 3,   ot_ear,     ot_eax,     ot_ear,     ot_none,    "csne",
	op_csne_rs,     4, 3,   ot_ear,     ot_eas,     ot_ear,     ot_none,    "csne",
	op_csne_dr,     5, 3,   ot_ead,     ot_ear,     ot_ear,     ot_none,    "csne",
	op_csne_xr,     5, 3,   ot_eax,     ot_ear,     ot_ear,     ot_none,    "csne",
	op_csne_sr,     4, 3,   ot_eas,     ot_ear,     ot_ear,     ot_none,    "csne",
	op_csgt_rr,     4, 3,   ot_ear,     ot_ear,     ot_ear,     ot_none,    "csgt",
	op_csgt_rd,     5, 3,   ot_ear,     ot_ead,     ot_ear,     ot_none,    "csgt",
	op_csgt_rx,     5, 3,   ot_ear,     ot_eax,     ot_ear,     ot_none,    "csgt",
	op_csgt_rs,     4, 3,   ot_ear,     ot_eas,     ot_ear,     ot_none,    "csgt",
	op_csgt_dr,     5, 3,   ot_ead,     ot_ear,     ot_ear,     ot_none,    "csgt",
	op_csgt_xr,     5, 3,   ot_eax,     ot_ear,     ot_ear,     ot_none,    "csgt",
	op_csgt_sr,     4, 3,   ot_eas,     ot_ear,     ot_ear,     ot_none,    "csgt",
	op_csge_rr,     4, 3,   ot_ear,     ot_ear,     ot_ear,     ot_none,    "csge",
	op_csge_rd,     5, 3,   ot_ear,     ot_ead,     ot_ear,     ot_none,    "csge",
	op_csge_rx,     5, 3,   ot_ear,     ot_eax,     ot_ear,     ot_none,    "csge",
	op_csge_rs,     4, 3,   ot_ear,     ot_eas,     ot_ear,     ot_none,    "csge",
	op_csge_dr,     5, 3,   ot_ead,     ot_ear,     ot_ear,     ot_none,    "csge",
	op_csge_xr,     5, 3,   ot_eax,     ot_ear,     ot_ear,     ot_none,    "csge",
	op_csge_sr,     4, 3,   ot_eas,     ot_ear,     ot_ear,     ot_none,    "csge",
	op_cslt_rr,     4, 3,   ot_ear,     ot_ear,     ot_ear,     ot_none,    "cslt",
	op_cslt_rd,     5, 3,   ot_ear,     ot_ead,     ot_ear,     ot_none,    "cslt",
	op_cslt_rx,     5, 3,   ot_ear,     ot_eax,     ot_ear,     ot_none,    "cslt",
	op_cslt_rs,     4, 3,   ot_ear,     ot_eas,     ot_ear,     ot_none,    "cslt",
	op_cslt_dr,     5, 3,   ot_ead,     ot_ear,     ot_ear,     ot_none,    "cslt",
	op_cslt_xr,     5, 3,   ot_eax,     ot_ear,     ot_ear,     ot_none,    "cslt",
	op_cslt_sr,     4, 3,   ot_eas,     ot_ear,     ot_ear,     ot_none,    "cslt",
	op_csle_rr,     4, 3,   ot_ear,     ot_ear,     ot_ear,     ot_none,    "csle",
	op_csle_rd,     5, 3,   ot_ear,     ot_ead,     ot_ear,     ot_none,    "csle",
	op_csle_rx,     5, 3,   ot_ear,     ot_eax,     ot_ear,     ot_none,    "csle",
	op_csle_rs,     4, 3,   ot_ear,     ot_eas,     ot_ear,     ot_none,    "csle",
	op_csle_dr,     5, 3,   ot_ead,     ot_ear,     ot_ear,     ot_none,    "csle",
	op_csle_xr,     5, 3,   ot_eax,     ot_ear,     ot_ear,     ot_none,    "csle",
	op_csle_sr,     4, 3,   ot_eas,     ot_ear,     ot_ear,     ot_none,    "csle",

	// extensions 2004/12/06
	op_snul_rr,     3, 2,   ot_ear,     ot_ear,     ot_none,    ot_none,    "snul",
	op_snnul_rr,    3, 2,   ot_ear,     ot_ear,     ot_none,    ot_none,    "snnul",
	op_unot_r,      2, 1,   ot_ear,     ot_none,    ot_none,    ot_none,    "unot",
	op_unot_d,      3, 1,   ot_ead,     ot_none,    ot_none,    ot_none,    "unot",
	op_unot_x,      3, 1,   ot_eax,     ot_none,    ot_none,    ot_none,    "unot",
	op_unot_s,      2, 1,   ot_eas,     ot_none,    ot_none,    ot_none,    "unot",

	// extensions 2004/12/16
	op_streq_rr,    4, 3,   ot_ear,     ot_ear,     ot_ear,     ot_none,    "streq",
	op_streq_rd,    5, 3,   ot_ear,     ot_ead,     ot_ear,     ot_none,    "streq",
	op_streq_rx,    5, 3,   ot_ear,     ot_eax,     ot_ear,     ot_none,    "streq",
	op_streq_rs,    4, 3,   ot_ear,     ot_eas,     ot_ear,     ot_none,    "streq",
	op_streq_dr,    5, 3,   ot_ead,     ot_ear,     ot_ear,     ot_none,    "streq",
	op_streq_xr,    5, 3,   ot_eax,     ot_ear,     ot_ear,     ot_none,    "streq",
	op_streq_sr,    4, 3,   ot_eas,     ot_ear,     ot_ear,     ot_none,    "streq",
	op_strne_rr,    4, 3,   ot_ear,     ot_ear,     ot_ear,     ot_none,    "strne",
	op_strne_rd,    5, 3,   ot_ear,     ot_ead,     ot_ear,     ot_none,    "strne",
	op_strne_rx,    5, 3,   ot_ear,     ot_eax,     ot_ear,     ot_none,    "strne",
	op_strne_rs,    4, 3,   ot_ear,     ot_eas,     ot_ear,     ot_none,    "strne",
	op_strne_dr,    5, 3,   ot_ead,     ot_ear,     ot_ear,     ot_none,    "strne",
	op_strne_xr,    5, 3,   ot_eax,     ot_ear,     ot_ear,     ot_none,    "strne",
	op_strne_sr,    4, 3,   ot_eas,     ot_ear,     ot_ear,     ot_none,    "strne",
	op_stradd_rr,   3, 2,   ot_ear,     ot_ear,     ot_none,    ot_none,    "stradd",
	op_stradd_rd,   4, 2,   ot_ear,     ot_ead,     ot_none,    ot_none,    "stradd",
	op_stradd_rx,   4, 2,   ot_ear,     ot_eax,     ot_none,    ot_none,    "stradd",
	op_stradd_rs,   3, 2,   ot_ear,     ot_eas,     ot_none,    ot_none,    "stradd",
	op_stradd_dr,   4, 2,   ot_ead,     ot_ear,     ot_none,    ot_none,    "stradd",
	op_stradd_xr,   4, 2,   ot_eax,     ot_ear,     ot_none,    ot_none,    "stradd",
	op_stradd_sr,   3, 2,   ot_eas,     ot_ear,     ot_none,    ot_none,    "stradd",
	op_arrcp_rr,    3, 2,   ot_ear,     ot_ear,     ot_none,    ot_none,    "arrcp",
	op_arrcp_rd,    4, 2,   ot_ear,     ot_ead,     ot_none,    ot_none,    "arrcp",
	op_arrcp_rx,    4, 2,   ot_ear,     ot_eax,     ot_none,    ot_none,    "arrcp",
	op_arrcp_rs,    3, 2,   ot_ear,     ot_eas,     ot_none,    ot_none,    "arrcp",
	op_arrcp_dr,    4, 2,   ot_ead,     ot_ear,     ot_none,    ot_none,    "arrcp",
	op_arrcp_xr,    4, 2,   ot_eax,     ot_ear,     ot_none,    ot_none,    "arrcp",
	op_arrcp_sr,    3, 2,   ot_eas,     ot_ear,     ot_none,    ot_none,    "arrcp",
	op_arrmv_rr,    3, 2,   ot_ear,     ot_ear,     ot_none,    ot_none,    "arrmv",
	op_arrmv_rd,    4, 2,   ot_ear,     ot_ead,     ot_none,    ot_none,    "arrmv",
	op_arrmv_rx,    4, 2,   ot_ear,     ot_eax,     ot_none,    ot_none,    "arrmv",
	op_arrmv_rs,    3, 2,   ot_ear,     ot_eas,     ot_none,    ot_none,    "arrmv",
	op_arrmv_dr,    4, 2,   ot_ead,     ot_ear,     ot_none,    ot_none,    "arrmv",
	op_arrmv_xr,    4, 2,   ot_eax,     ot_ear,     ot_none,    ot_none,    "arrmv",
	op_arrmv_sr,    3, 2,   ot_eas,     ot_ear,     ot_none,    ot_none,    "arrmv",

	// extensions 2005/02/19
	op_addl_rr,     3, 2,   ot_ear,     ot_ear,     ot_none,    ot_none,    "addl",
	op_addl_rd,     4, 2,   ot_ear,     ot_ead,     ot_none,    ot_none,    "addl",
	op_addl_rx,     4, 2,   ot_ear,     ot_eax,     ot_none,    ot_none,    "addl",
	op_addl_rs,     3, 2,   ot_ear,     ot_eas,     ot_none,    ot_none,    "addl",
	op_addl_dr,     4, 2,   ot_ead,     ot_ear,     ot_none,    ot_none,    "addl",
	op_addl_xr,     4, 2,   ot_eax,     ot_ear,     ot_none,    ot_none,    "addl",
	op_addl_sr,     3, 2,   ot_eas,     ot_ear,     ot_none,    ot_none,    "addl",
	op_subl_rr,     3, 2,   ot_ear,     ot_ear,     ot_none,    ot_none,    "subl",
	op_subl_rd,     4, 2,   ot_ear,     ot_ead,     ot_none,    ot_none,    "subl",
	op_subl_rx,     4, 2,   ot_ear,     ot_eax,     ot_none,    ot_none,    "subl",
	op_subl_rs,     3, 2,   ot_ear,     ot_eas,     ot_none,    ot_none,    "subl",
	op_subl_dr,     4, 2,   ot_ead,     ot_ear,     ot_none,    ot_none,    "subl",
	op_subl_xr,     4, 2,   ot_eax,     ot_ear,     ot_none,    ot_none,    "subl",
	op_subl_sr,     3, 2,   ot_eas,     ot_ear,     ot_none,    ot_none,    "subl",
	op_mull_rr,     3, 2,   ot_ear,     ot_ear,     ot_none,    ot_none,    "mull",
	op_mull_rd,     4, 2,   ot_ear,     ot_ead,     ot_none,    ot_none,    "mull",
	op_mull_rx,     4, 2,   ot_ear,     ot_eax,     ot_none,    ot_none,    "mull",
	op_mull_rs,     3, 2,   ot_ear,     ot_eas,     ot_none,    ot_none,    "mull",
	op_mull_dr,     4, 2,   ot_ead,     ot_ear,     ot_none,    ot_none,    "mull",
	op_mull_xr,     4, 2,   ot_eax,     ot_ear,     ot_none,    ot_none,    "mull",
	op_mull_sr,     3, 2,   ot_eas,     ot_ear,     ot_none,    ot_none,    "mull",
	op_divl_rr,     3, 2,   ot_ear,     ot_ear,     ot_none,    ot_none,    "divl",
	op_divl_rd,     4, 2,   ot_ear,     ot_ead,     ot_none,    ot_none,    "divl",
	op_divl_rx,     4, 2,   ot_ear,     ot_eax,     ot_none,    ot_none,    "divl",
	op_divl_rs,     3, 2,   ot_ear,     ot_eas,     ot_none,    ot_none,    "divl",
	op_divl_dr,     4, 2,   ot_ead,     ot_ear,     ot_none,    ot_none,    "divl",
	op_divl_xr,     4, 2,   ot_eax,     ot_ear,     ot_none,    ot_none,    "divl",
	op_divl_sr,     3, 2,   ot_eas,     ot_ear,     ot_none,    ot_none,    "divl",
	op_modl_rr,     3, 2,   ot_ear,     ot_ear,     ot_none,    ot_none,    "modl",
	op_modl_rd,     4, 2,   ot_ear,     ot_ead,     ot_none,    ot_none,    "modl",
	op_modl_rx,     4, 2,   ot_ear,     ot_eax,     ot_none,    ot_none,    "modl",
	op_modl_rs,     3, 2,   ot_ear,     ot_eas,     ot_none,    ot_none,    "modl",
	op_modl_dr,     4, 2,   ot_ead,     ot_ear,     ot_none,    ot_none,    "modl",
	op_modl_xr,     4, 2,   ot_eax,     ot_ear,     ot_none,    ot_none,    "modl",
	op_modl_sr,     3, 2,   ot_eas,     ot_ear,     ot_none,    ot_none,    "modl",
	op_decl_r,      2, 1,   ot_ear,     ot_none,    ot_none,    ot_none,    "decl",
	op_decl_d,      3, 1,   ot_ead,     ot_none,    ot_none,    ot_none,    "decl",
	op_decl_x,      3, 1,   ot_eax,     ot_none,    ot_none,    ot_none,    "decl",
	op_decl_s,      2, 1,   ot_eas,     ot_none,    ot_none,    ot_none,    "decl",
	op_incl_r,      2, 1,   ot_ear,     ot_none,    ot_none,    ot_none,    "incl",
	op_incl_d,      3, 1,   ot_ead,     ot_none,    ot_none,    ot_none,    "incl",
	op_incl_x,      3, 1,   ot_eax,     ot_none,    ot_none,    ot_none,    "incl",
	op_incl_s,      2, 1,   ot_eas,     ot_none,    ot_none,    ot_none,    "incl",
	op_negl_r,      2, 1,   ot_ear,     ot_none,    ot_none,    ot_none,    "negl",
	op_negl_d,      3, 1,   ot_ead,     ot_none,    ot_none,    ot_none,    "negl",
	op_negl_x,      3, 1,   ot_eax,     ot_none,    ot_none,    ot_none,    "negl",
	op_negl_s,      2, 1,   ot_eas,     ot_none,    ot_none,    ot_none,    "negl",
	op_cseql_rr,    4, 3,   ot_ear,     ot_ear,     ot_ear,     ot_none,    "cseql",
	op_cseql_rd,    5, 3,   ot_ear,     ot_ead,     ot_ear,     ot_none,    "cseql",
	op_cseql_rx,    5, 3,   ot_ear,     ot_eax,     ot_ear,     ot_none,    "cseql",
	op_cseql_rs,    4, 3,   ot_ear,     ot_eas,     ot_ear,     ot_none,    "cseql",
	op_cseql_dr,    5, 3,   ot_ead,     ot_ear,     ot_ear,     ot_none,    "cseql",
	op_cseql_xr,    5, 3,   ot_eax,     ot_ear,     ot_ear,     ot_none,    "cseql",
	op_cseql_sr,    4, 3,   ot_eas,     ot_ear,     ot_ear,     ot_none,    "cseql",
	op_csnel_rr,    4, 3,   ot_ear,     ot_ear,     ot_ear,     ot_none,    "csnel",
	op_csnel_rd,    5, 3,   ot_ear,     ot_ead,     ot_ear,     ot_none,    "csnel",
	op_csnel_rx,    5, 3,   ot_ear,     ot_eax,     ot_ear,     ot_none,    "csnel",
	op_csnel_rs,    4, 3,   ot_ear,     ot_eas,     ot_ear,     ot_none,    "csnel",
	op_csnel_dr,    5, 3,   ot_ead,     ot_ear,     ot_ear,     ot_none,    "csnel",
	op_csnel_xr,    5, 3,   ot_eax,     ot_ear,     ot_ear,     ot_none,    "csnel",
	op_csnel_sr,    4, 3,   ot_eas,     ot_ear,     ot_ear,     ot_none,    "csnel",
	op_csgtl_rr,    4, 3,   ot_ear,     ot_ear,     ot_ear,     ot_none,    "csgtl",
	op_csgtl_rd,    5, 3,   ot_ear,     ot_ead,     ot_ear,     ot_none,    "csgtl",
	op_csgtl_rx,    5, 3,   ot_ear,     ot_eax,     ot_ear,     ot_none,    "csgtl",
	op_csgtl_rs,    4, 3,   ot_ear,     ot_eas,     ot_ear,     ot_none,    "csgtl",
	op_csgtl_dr,    5, 3,   ot_ead,     ot_ear,     ot_ear,     ot_none,    "csgtl",
	op_csgtl_xr,    5, 3,   ot_eax,     ot_ear,     ot_ear,     ot_none,    "csgtl",
	op_csgtl_sr,    4, 3,   ot_eas,     ot_ear,     ot_ear,     ot_none,    "csgtl",
	op_csgel_rr,    4, 3,   ot_ear,     ot_ear,     ot_ear,     ot_none,    "csgel",
	op_csgel_rd,    5, 3,   ot_ear,     ot_ead,     ot_ear,     ot_none,    "csgel",
	op_csgel_rx,    5, 3,   ot_ear,     ot_eax,     ot_ear,     ot_none,    "csgel",
	op_csgel_rs,    4, 3,   ot_ear,     ot_eas,     ot_ear,     ot_none,    "csgel",
	op_csgel_dr,    5, 3,   ot_ead,     ot_ear,     ot_ear,     ot_none,    "csgel",
	op_csgel_xr,    5, 3,   ot_eax,     ot_ear,     ot_ear,     ot_none,    "csgel",
	op_csgel_sr,    4, 3,   ot_eas,     ot_ear,     ot_ear,     ot_none,    "csgel",
	op_csltl_rr,    4, 3,   ot_ear,     ot_ear,     ot_ear,     ot_none,    "csltl",
	op_csltl_rd,    5, 3,   ot_ear,     ot_ead,     ot_ear,     ot_none,    "csltl",
	op_csltl_rx,    5, 3,   ot_ear,     ot_eax,     ot_ear,     ot_none,    "csltl",
	op_csltl_rs,    4, 3,   ot_ear,     ot_eas,     ot_ear,     ot_none,    "csltl",
	op_csltl_dr,    5, 3,   ot_ead,     ot_ear,     ot_ear,     ot_none,    "csltl",
	op_csltl_xr,    5, 3,   ot_eax,     ot_ear,     ot_ear,     ot_none,    "csltl",
	op_csltl_sr,    4, 3,   ot_eas,     ot_ear,     ot_ear,     ot_none,    "csltl",
	op_cslel_rr,    4, 3,   ot_ear,     ot_ear,     ot_ear,     ot_none,    "cslel",
	op_cslel_rd,    5, 3,   ot_ear,     ot_ead,     ot_ear,     ot_none,    "cslel",
	op_cslel_rx,    5, 3,   ot_ear,     ot_eax,     ot_ear,     ot_none,    "cslel",
	op_cslel_rs,    4, 3,   ot_ear,     ot_eas,     ot_ear,     ot_none,    "cslel",
	op_cslel_dr,    5, 3,   ot_ead,     ot_ear,     ot_ear,     ot_none,    "cslel",
	op_cslel_xr,    5, 3,   ot_eax,     ot_ear,     ot_ear,     ot_none,    "cslel",
	op_cslel_sr,    4, 3,   ot_eas,     ot_ear,     ot_ear,     ot_none,    "cslel",

	op_addf_rr,     3, 2,   ot_ear,     ot_ear,     ot_none,    ot_none,    "addf",
	op_addf_rd,     4, 2,   ot_ear,     ot_ead,     ot_none,    ot_none,    "addf",
	op_addf_rx,     4, 2,   ot_ear,     ot_eax,     ot_none,    ot_none,    "addf",
	op_addf_rs,     3, 2,   ot_ear,     ot_eas,     ot_none,    ot_none,    "addf",
	op_addf_dr,     4, 2,   ot_ead,     ot_ear,     ot_none,    ot_none,    "addf",
	op_addf_xr,     4, 2,   ot_eax,     ot_ear,     ot_none,    ot_none,    "addf",
	op_addf_sr,     3, 2,   ot_eas,     ot_ear,     ot_none,    ot_none,    "addf",
	op_subf_rr,     3, 2,   ot_ear,     ot_ear,     ot_none,    ot_none,    "subf",
	op_subf_rd,     4, 2,   ot_ear,     ot_ead,     ot_none,    ot_none,    "subf",
	op_subf_rx,     4, 2,   ot_ear,     ot_eax,     ot_none,    ot_none,    "subf",
	op_subf_rs,     3, 2,   ot_ear,     ot_eas,     ot_none,    ot_none,    "subf",
	op_subf_dr,     4, 2,   ot_ead,     ot_ear,     ot_none,    ot_none,    "subf",
	op_subf_xr,     4, 2,   ot_eax,     ot_ear,     ot_none,    ot_none,    "subf",
	op_subf_sr,     3, 2,   ot_eas,     ot_ear,     ot_none,    ot_none,    "subf",
	op_mulf_rr,     3, 2,   ot_ear,     ot_ear,     ot_none,    ot_none,    "mulf",
	op_mulf_rd,     4, 2,   ot_ear,     ot_ead,     ot_none,    ot_none,    "mulf",
	op_mulf_rx,     4, 2,   ot_ear,     ot_eax,     ot_none,    ot_none,    "mulf",
	op_mulf_rs,     3, 2,   ot_ear,     ot_eas,     ot_none,    ot_none,    "mulf",
	op_mulf_dr,     4, 2,   ot_ead,     ot_ear,     ot_none,    ot_none,    "mulf",
	op_mulf_xr,     4, 2,   ot_eax,     ot_ear,     ot_none,    ot_none,    "mulf",
	op_mulf_sr,     3, 2,   ot_eas,     ot_ear,     ot_none,    ot_none,    "mulf",
	op_divf_rr,     3, 2,   ot_ear,     ot_ear,     ot_none,    ot_none,    "divf",
	op_divf_rd,     4, 2,   ot_ear,     ot_ead,     ot_none,    ot_none,    "divf",
	op_divf_rx,     4, 2,   ot_ear,     ot_eax,     ot_none,    ot_none,    "divf",
	op_divf_rs,     3, 2,   ot_ear,     ot_eas,     ot_none,    ot_none,    "divf",
	op_divf_dr,     4, 2,   ot_ead,     ot_ear,     ot_none,    ot_none,    "divf",
	op_divf_xr,     4, 2,   ot_eax,     ot_ear,     ot_none,    ot_none,    "divf",
	op_divf_sr,     3, 2,   ot_eas,     ot_ear,     ot_none,    ot_none,    "divf",
	op_modf_rr,     3, 2,   ot_ear,     ot_ear,     ot_none,    ot_none,    "modf",
	op_modf_rd,     4, 2,   ot_ear,     ot_ead,     ot_none,    ot_none,    "modf",
	op_modf_rx,     4, 2,   ot_ear,     ot_eax,     ot_none,    ot_none,    "modf",
	op_modf_rs,     3, 2,   ot_ear,     ot_eas,     ot_none,    ot_none,    "modf",
	op_modf_dr,     4, 2,   ot_ead,     ot_ear,     ot_none,    ot_none,    "modf",
	op_modf_xr,     4, 2,   ot_eax,     ot_ear,     ot_none,    ot_none,    "modf",
	op_modf_sr,     3, 2,   ot_eas,     ot_ear,     ot_none,    ot_none,    "modf",
	op_decf_r,      2, 1,   ot_ear,     ot_none,    ot_none,    ot_none,    "decf",
	op_decf_d,      3, 1,   ot_ead,     ot_none,    ot_none,    ot_none,    "decf",
	op_decf_x,      3, 1,   ot_eax,     ot_none,    ot_none,    ot_none,    "decf",
	op_decf_s,      2, 1,   ot_eas,     ot_none,    ot_none,    ot_none,    "decf",
	op_incf_r,      2, 1,   ot_ear,     ot_none,    ot_none,    ot_none,    "incf",
	op_incf_d,      3, 1,   ot_ead,     ot_none,    ot_none,    ot_none,    "incf",
	op_incf_x,      3, 1,   ot_eax,     ot_none,    ot_none,    ot_none,    "incf",
	op_incf_s,      2, 1,   ot_eas,     ot_none,    ot_none,    ot_none,    "incf",
	op_negf_r,      2, 1,   ot_ear,     ot_none,    ot_none,    ot_none,    "negf",
	op_negf_d,      3, 1,   ot_ead,     ot_none,    ot_none,    ot_none,    "negf",
	op_negf_x,      3, 1,   ot_eax,     ot_none,    ot_none,    ot_none,    "negf",
	op_negf_s,      2, 1,   ot_eas,     ot_none,    ot_none,    ot_none,    "negf",
	op_cseqf_rr,    4, 3,   ot_ear,     ot_ear,     ot_ear,     ot_none,    "cseqf",
	op_cseqf_rd,    5, 3,   ot_ear,     ot_ead,     ot_ear,     ot_none,    "cseqf",
	op_cseqf_rx,    5, 3,   ot_ear,     ot_eax,     ot_ear,     ot_none,    "cseqf",
	op_cseqf_rs,    4, 3,   ot_ear,     ot_eas,     ot_ear,     ot_none,    "cseqf",
	op_cseqf_dr,    5, 3,   ot_ead,     ot_ear,     ot_ear,     ot_none,    "cseqf",
	op_cseqf_xr,    5, 3,   ot_eax,     ot_ear,     ot_ear,     ot_none,    "cseqf",
	op_cseqf_sr,    4, 3,   ot_eas,     ot_ear,     ot_ear,     ot_none,    "cseqf",
	op_csnef_rr,    4, 3,   ot_ear,     ot_ear,     ot_ear,     ot_none,    "csnef",
	op_csnef_rd,    5, 3,   ot_ear,     ot_ead,     ot_ear,     ot_none,    "csnef",
	op_csnef_rx,    5, 3,   ot_ear,     ot_eax,     ot_ear,     ot_none,    "csnef",
	op_csnef_rs,    4, 3,   ot_ear,     ot_eas,     ot_ear,     ot_none,    "csnef",
	op_csnef_dr,    5, 3,   ot_ead,     ot_ear,     ot_ear,     ot_none,    "csnef",
	op_csnef_xr,    5, 3,   ot_eax,     ot_ear,     ot_ear,     ot_none,    "csnef",
	op_csnef_sr,    4, 3,   ot_eas,     ot_ear,     ot_ear,     ot_none,    "csnef",
	op_csgtf_rr,    4, 3,   ot_ear,     ot_ear,     ot_ear,     ot_none,    "csgtf",
	op_csgtf_rd,    5, 3,   ot_ear,     ot_ead,     ot_ear,     ot_none,    "csgtf",
	op_csgtf_rx,    5, 3,   ot_ear,     ot_eax,     ot_ear,     ot_none,    "csgtf",
	op_csgtf_rs,    4, 3,   ot_ear,     ot_eas,     ot_ear,     ot_none,    "csgtf",
	op_csgtf_dr,    5, 3,   ot_ead,     ot_ear,     ot_ear,     ot_none,    "csgtf",
	op_csgtf_xr,    5, 3,   ot_eax,     ot_ear,     ot_ear,     ot_none,    "csgtf",
	op_csgtf_sr,    4, 3,   ot_eas,     ot_ear,     ot_ear,     ot_none,    "csgtf",
	op_csgef_rr,    4, 3,   ot_ear,     ot_ear,     ot_ear,     ot_none,    "csgef",
	op_csgef_rd,    5, 3,   ot_ear,     ot_ead,     ot_ear,     ot_none,    "csgef",
	op_csgef_rx,    5, 3,   ot_ear,     ot_eax,     ot_ear,     ot_none,    "csgef",
	op_csgef_rs,    4, 3,   ot_ear,     ot_eas,     ot_ear,     ot_none,    "csgef",
	op_csgef_dr,    5, 3,   ot_ead,     ot_ear,     ot_ear,     ot_none,    "csgef",
	op_csgef_xr,    5, 3,   ot_eax,     ot_ear,     ot_ear,     ot_none,    "csgef",
	op_csgef_sr,    4, 3,   ot_eas,     ot_ear,     ot_ear,     ot_none,    "csgef",
	op_csltf_rr,    4, 3,   ot_ear,     ot_ear,     ot_ear,     ot_none,    "csltf",
	op_csltf_rd,    5, 3,   ot_ear,     ot_ead,     ot_ear,     ot_none,    "csltf",
	op_csltf_rx,    5, 3,   ot_ear,     ot_eax,     ot_ear,     ot_none,    "csltf",
	op_csltf_rs,    4, 3,   ot_ear,     ot_eas,     ot_ear,     ot_none,    "csltf",
	op_csltf_dr,    5, 3,   ot_ead,     ot_ear,     ot_ear,     ot_none,    "csltf",
	op_csltf_xr,    5, 3,   ot_eax,     ot_ear,     ot_ear,     ot_none,    "csltf",
	op_csltf_sr,    4, 3,   ot_eas,     ot_ear,     ot_ear,     ot_none,    "csltf",
	op_cslef_rr,    4, 3,   ot_ear,     ot_ear,     ot_ear,     ot_none,    "cslef",
	op_cslef_rd,    5, 3,   ot_ear,     ot_ead,     ot_ear,     ot_none,    "cslef",
	op_cslef_rx,    5, 3,   ot_ear,     ot_eax,     ot_ear,     ot_none,    "cslef",
	op_cslef_rs,    4, 3,   ot_ear,     ot_eas,     ot_ear,     ot_none,    "cslef",
	op_cslef_dr,    5, 3,   ot_ead,     ot_ear,     ot_ear,     ot_none,    "cslef",
	op_cslef_xr,    5, 3,   ot_eax,     ot_ear,     ot_ear,     ot_none,    "cslef",
	op_cslef_sr,    4, 3,   ot_eas,     ot_ear,     ot_ear,     ot_none,    "cslef",

	// extensions 2005-03-28
	op_pop,         1, 0,   ot_none,    ot_none,    ot_none,    ot_none,    "pop",
	op_push,        1, 0,   ot_none,    ot_none,    ot_none,    ot_none,    "push",

	// extensions 2005-11-12
	op_rtchk_r,     3, 2,   ot_type,    ot_ear,     ot_none,    ot_none,    "rtchk",
	op_rtchk_d,     4, 2,   ot_type,    ot_ead,     ot_none,    ot_none,    "rtchk",
	op_rtchk_x,     4, 2,   ot_type,    ot_eax,     ot_none,    ot_none,    "rtchk",
	op_rtchk_s,     3, 2,   ot_type,    ot_eas,     ot_none,    ot_none,    "rtchk",

	// extensions 2005-11-25
	op_jsr,         2, 1,   ot_number,  ot_none,    ot_none,    ot_none,    "jsr",
	op_jsr_r,       2, 1,   ot_ear,     ot_none,    ot_none,    ot_none,    "jsr",
	op_jsr_d,       3, 1,   ot_ead,     ot_none,    ot_none,    ot_none,    "jsr",
	op_jsr_x,       3, 1,   ot_eax,     ot_none,    ot_none,    ot_none,    "jsr",
	op_jsr_s,       2, 1,   ot_eas,     ot_none,    ot_none,    ot_none,    "jsr",

	// extensions 2006-07-01
	op_newctx,      5, 4,   ot_type,    ot_number,  ot_number,  ot_ear,     "newctx",
	op_resume_r,    2, 1,   ot_ear,     ot_none,    ot_none,    ot_none,    "resume",
	op_resume_d,    3, 1,   ot_ead,     ot_none,    ot_none,    ot_none,    "resume",
	op_resume_x,    3, 1,   ot_eax,     ot_none,    ot_none,    ot_none,    "resume",
	op_resume_s,    2, 1,   ot_eas,     ot_none,    ot_none,    ot_none,    "resume",
	op_yield,       1, 0,   ot_none,    ot_none,    ot_none,    ot_none,    "yield",

	// extensions 2006-07-12, "weak references"
	op_wref_rr,     3, 2,   ot_ear,     ot_ear,     ot_none,    ot_none,    "wref",
	op_wref_rd,     4, 2,   ot_ear,     ot_ead,     ot_none,    ot_none,    "wref",
	op_wref_rx,     4, 2,   ot_ear,     ot_eax,     ot_none,    ot_none,    "wref",
	op_wref_rs,     3, 2,   ot_ear,     ot_eas,     ot_none,    ot_none,    "wref",
	op_wref_dr,     4, 2,   ot_ead,     ot_ear,     ot_none,    ot_none,    "wref",
	op_wref_dd,     5, 2,   ot_ead,     ot_ead,     ot_none,    ot_none,    "wref",
	op_wref_dx,     5, 2,   ot_ead,     ot_eax,     ot_none,    ot_none,    "wref",
	op_wref_ds,     4, 2,   ot_ead,     ot_eas,     ot_none,    ot_none,    "wref",
	op_wref_xr,     4, 2,   ot_eax,     ot_ear,     ot_none,    ot_none,    "wref",
	op_wref_xd,     5, 2,   ot_eax,     ot_ead,     ot_none,    ot_none,    "wref",
	op_wref_xx,     5, 2,   ot_eax,     ot_eax,     ot_none,    ot_none,    "wref",
	op_wref_xs,     4, 2,   ot_eax,     ot_eas,     ot_none,    ot_none,    "wref",
	op_wref_sr,     3, 2,   ot_eas,     ot_ear,     ot_none,    ot_none,    "wref",
	op_wref_sd,     4, 2,   ot_eas,     ot_ead,     ot_none,    ot_none,    "wref",
	op_wref_sx,     4, 2,   ot_eas,     ot_eax,     ot_none,    ot_none,    "wref",
	op_wref_ss,     3, 2,   ot_eas,     ot_eas,     ot_none,    ot_none,    "wref",

	// extensions 2007-09-13
	op_cmpref_rr,   4, 3,   ot_ear,     ot_ear,     ot_ear,     ot_none,    "cmpref",

	// extensions 2008-04-13
	op_newdg,       4, 3,   ot_type,    ot_number,  ot_ear,     ot_none,    "newdg",
	op_newdgm,      5, 4,   ot_type,    ot_number,  ot_ear,     ot_ear,     "newdgm",
	op_calldg_r,    2, 1,   ot_ear,     ot_none,    ot_none,    ot_none,    "calldg",
	op_calldg_d,    3, 1,   ot_ead,     ot_none,    ot_none,    ot_none,    "calldg",
	op_calldg_x,    3, 1,   ot_eax,     ot_none,    ot_none,    ot_none,    "calldg",
	op_calldg_s,    2, 1,   ot_eas,     ot_none,    ot_none,    ot_none,    "calldg",

	// extensions 2010-02-15
	op_throw,       1, 0,   ot_none,    ot_none,    ot_none,    ot_none,    "throw",

	// extensions 2014-04
	op_alloci,      3, 2,   ot_type,    ot_ear,     ot_none,    ot_none,    "alloci",
	op_calli,       3, 2,   ot_type,    ot_number,  ot_none,    ot_none,    "calli",
	op_dcvt,        4, 3,   ot_type,    ot_ear,     ot_ear,     ot_none,    "dcvt",

	// extensions 2015-01-01
	op_newdgc,      5, 4,   ot_type,    ot_number,  ot_number,  ot_ear,     "newdgc"
};
