//------------------------------------------------------------------------------
// File: JILOpCodes.h                                       (c) 2003 jewe.org
//------------------------------------------------------------------------------
//
// DISCLAIMER:
// -----------
//	THIS SOFTWARE IS SUBJECT TO THE LICENSE AGREEMENT FOUND IN "jilapi.h" AND
//	"COPYING". BY USING THIS SOFTWARE YOU IMPLICITLY DECLARE YOUR AGREEMENT TO
//	THE TERMS OF THIS LICENSE.
//
// Description:
// ------------
//	Defines the opcodes for JIL virtual machine instructions.
//------------------------------------------------------------------------------

#ifndef JILOPCODES_H
#define JILOPCODES_H

//------------------------------------------------------------------------------
// Opcodes
//------------------------------------------------------------------------------

enum
{
	op_nop = 0,	// code optimizer relies on 0 == NOP instruction!!!
    op_alloc,
    op_alloca,
    op_allocn,
    op_bra,
	op_brk,
    op_callm,
    op_calls,
    op_calln,
    op_cvf,
    op_cvl,
    op_popm,
    op_popr,
    op_pushm,
    op_pushr,
    op_ret,
    op_type,
	op_dec_r,
	op_dec_d,
	op_dec_x,
	op_dec_s,
	op_inc_r,
	op_inc_d,
	op_inc_x,
	op_inc_s,
    op_moveh_r,
    op_moveh_d,
    op_moveh_x,
    op_moveh_s,
    op_neg_r,
    op_neg_d,
    op_neg_x,
    op_neg_s,
    op_not_r,
    op_not_d,
    op_not_x,
    op_not_s,
	op_tsteq_r,
	op_tsteq_d,
	op_tsteq_x,
	op_tsteq_s,
	op_tstne_r,
	op_tstne_d,
	op_tstne_x,
	op_tstne_s,
    op_add_rr,
    op_add_rd,
    op_add_rx,
    op_add_rs,
    op_add_dr,
    op_add_xr,
    op_add_sr,
    op_and_rr,
    op_and_rd,
    op_and_rx,
    op_and_rs,
    op_and_dr,
    op_and_xr,
    op_and_sr,
    op_asl_rr,
    op_asl_rd,
    op_asl_rx,
    op_asl_rs,
    op_asl_dr,
    op_asl_xr,
    op_asl_sr,
    op_asr_rr,
    op_asr_rd,
    op_asr_rx,
    op_asr_rs,
    op_asr_dr,
    op_asr_xr,
    op_asr_sr,
    op_div_rr,
    op_div_rd,
    op_div_rx,
    op_div_rs,
    op_div_dr,
    op_div_xr,
    op_div_sr,
    op_lsl_rr,
    op_lsl_rd,
    op_lsl_rx,
    op_lsl_rs,
    op_lsl_dr,
    op_lsl_xr,
    op_lsl_sr,
    op_lsr_rr,
    op_lsr_rd,
    op_lsr_rx,
    op_lsr_rs,
    op_lsr_dr,
    op_lsr_xr,
    op_lsr_sr,
    op_mod_rr,
    op_mod_rd,
    op_mod_rx,
    op_mod_rs,
    op_mod_dr,
    op_mod_xr,
    op_mod_sr,
    op_mul_rr,
    op_mul_rd,
    op_mul_rx,
    op_mul_rs,
    op_mul_dr,
    op_mul_xr,
    op_mul_sr,
    op_or_rr,
    op_or_rd,
    op_or_rx,
    op_or_rs,
    op_or_dr,
    op_or_xr,
    op_or_sr,
    op_sub_rr,
    op_sub_rd,
    op_sub_rx,
    op_sub_rs,
    op_sub_dr,
    op_sub_xr,
    op_sub_sr,
    op_xor_rr,
    op_xor_rd,
    op_xor_rx,
    op_xor_rs,
    op_xor_dr,
    op_xor_xr,
    op_xor_sr,
    op_move_rr,
    op_move_rd,
    op_move_rx,
    op_move_rs,
    op_move_dr,
    op_move_dd,
    op_move_dx,
    op_move_ds,
    op_move_xr,
    op_move_xd,
    op_move_xx,
    op_move_xs,
    op_move_sr,
    op_move_sd,
    op_move_sx,
    op_move_ss,

	// extensions 2004/10/30
	op_ldz_r,

	// extensions 2004/11/10
    op_copy_rr,
    op_copy_rd,
    op_copy_rx,
    op_copy_rs,
    op_copy_dr,
    op_copy_dd,
    op_copy_dx,
    op_copy_ds,
    op_copy_xr,
    op_copy_xd,
    op_copy_xx,
    op_copy_xs,
    op_copy_sr,
    op_copy_sd,
    op_copy_sx,
    op_copy_ss,
	op_pop_r,
	op_pop_d,
	op_pop_x,
	op_pop_s,
	op_push_r,
	op_push_d,
	op_push_x,
	op_push_s,

	// extensions 2004/11/28
    op_copyh_r,
    op_copyh_d,
    op_copyh_x,
    op_copyh_s,
	op_cseq_rr,
	op_cseq_rd,
	op_cseq_rx,
	op_cseq_rs,
	op_cseq_dr,
	op_cseq_xr,
	op_cseq_sr,
	op_csne_rr,
	op_csne_rd,
	op_csne_rx,
	op_csne_rs,
	op_csne_dr,
	op_csne_xr,
	op_csne_sr,
	op_csgt_rr,
	op_csgt_rd,
	op_csgt_rx,
	op_csgt_rs,
	op_csgt_dr,
	op_csgt_xr,
	op_csgt_sr,
	op_csge_rr,
	op_csge_rd,
	op_csge_rx,
	op_csge_rs,
	op_csge_dr,
	op_csge_xr,
	op_csge_sr,
	op_cslt_rr,
	op_cslt_rd,
	op_cslt_rx,
	op_cslt_rs,
	op_cslt_dr,
	op_cslt_xr,
	op_cslt_sr,
	op_csle_rr,
	op_csle_rd,
	op_csle_rx,
	op_csle_rs,
	op_csle_dr,
	op_csle_xr,
	op_csle_sr,

	// extensions 2004/12/06
	op_snul_rr,
	op_snnul_rr,
    op_unot_r,
    op_unot_d,
    op_unot_x,
    op_unot_s,

	// extensions 2004/12/16
	op_streq_rr,
	op_streq_rd,
	op_streq_rx,
	op_streq_rs,
	op_streq_dr,
	op_streq_xr,
	op_streq_sr,
	op_strne_rr,
	op_strne_rd,
	op_strne_rx,
	op_strne_rs,
	op_strne_dr,
	op_strne_xr,
	op_strne_sr,
	op_stradd_rr,
	op_stradd_rd,
	op_stradd_rx,
	op_stradd_rs,
	op_stradd_dr,
	op_stradd_xr,
	op_stradd_sr,
	op_arrcp_rr,
	op_arrcp_rd,
	op_arrcp_rx,
	op_arrcp_rs,
	op_arrcp_dr,
	op_arrcp_xr,
	op_arrcp_sr,
	op_arrmv_rr,
	op_arrmv_rd,
	op_arrmv_rx,
	op_arrmv_rs,
	op_arrmv_dr,
	op_arrmv_xr,
	op_arrmv_sr,

	// extensions 2005/02/19
    op_addl_rr,
    op_addl_rd,
    op_addl_rx,
    op_addl_rs,
    op_addl_dr,
    op_addl_xr,
    op_addl_sr,
    op_subl_rr,
    op_subl_rd,
    op_subl_rx,
    op_subl_rs,
    op_subl_dr,
    op_subl_xr,
    op_subl_sr,
    op_mull_rr,
    op_mull_rd,
    op_mull_rx,
    op_mull_rs,
    op_mull_dr,
    op_mull_xr,
    op_mull_sr,
    op_divl_rr,
    op_divl_rd,
    op_divl_rx,
    op_divl_rs,
    op_divl_dr,
    op_divl_xr,
    op_divl_sr,
    op_modl_rr,
    op_modl_rd,
    op_modl_rx,
    op_modl_rs,
    op_modl_dr,
    op_modl_xr,
    op_modl_sr,
	op_decl_r,
	op_decl_d,
	op_decl_x,
	op_decl_s,
	op_incl_r,
	op_incl_d,
	op_incl_x,
	op_incl_s,
    op_negl_r,
    op_negl_d,
    op_negl_x,
    op_negl_s,
	op_cseql_rr,
	op_cseql_rd,
	op_cseql_rx,
	op_cseql_rs,
	op_cseql_dr,
	op_cseql_xr,
	op_cseql_sr,
	op_csnel_rr,
	op_csnel_rd,
	op_csnel_rx,
	op_csnel_rs,
	op_csnel_dr,
	op_csnel_xr,
	op_csnel_sr,
	op_csgtl_rr,
	op_csgtl_rd,
	op_csgtl_rx,
	op_csgtl_rs,
	op_csgtl_dr,
	op_csgtl_xr,
	op_csgtl_sr,
	op_csgel_rr,
	op_csgel_rd,
	op_csgel_rx,
	op_csgel_rs,
	op_csgel_dr,
	op_csgel_xr,
	op_csgel_sr,
	op_csltl_rr,
	op_csltl_rd,
	op_csltl_rx,
	op_csltl_rs,
	op_csltl_dr,
	op_csltl_xr,
	op_csltl_sr,
	op_cslel_rr,
	op_cslel_rd,
	op_cslel_rx,
	op_cslel_rs,
	op_cslel_dr,
	op_cslel_xr,
	op_cslel_sr,

    op_addf_rr,
    op_addf_rd,
    op_addf_rx,
    op_addf_rs,
    op_addf_dr,
    op_addf_xr,
    op_addf_sr,
    op_subf_rr,
    op_subf_rd,
    op_subf_rx,
    op_subf_rs,
    op_subf_dr,
    op_subf_xr,
    op_subf_sr,
    op_mulf_rr,
    op_mulf_rd,
    op_mulf_rx,
    op_mulf_rs,
    op_mulf_dr,
    op_mulf_xr,
    op_mulf_sr,
    op_divf_rr,
    op_divf_rd,
    op_divf_rx,
    op_divf_rs,
    op_divf_dr,
    op_divf_xr,
    op_divf_sr,
    op_modf_rr,
    op_modf_rd,
    op_modf_rx,
    op_modf_rs,
    op_modf_dr,
    op_modf_xr,
    op_modf_sr,
	op_decf_r,
	op_decf_d,
	op_decf_x,
	op_decf_s,
	op_incf_r,
	op_incf_d,
	op_incf_x,
	op_incf_s,
    op_negf_r,
    op_negf_d,
    op_negf_x,
    op_negf_s,
	op_cseqf_rr,
	op_cseqf_rd,
	op_cseqf_rx,
	op_cseqf_rs,
	op_cseqf_dr,
	op_cseqf_xr,
	op_cseqf_sr,
	op_csnef_rr,
	op_csnef_rd,
	op_csnef_rx,
	op_csnef_rs,
	op_csnef_dr,
	op_csnef_xr,
	op_csnef_sr,
	op_csgtf_rr,
	op_csgtf_rd,
	op_csgtf_rx,
	op_csgtf_rs,
	op_csgtf_dr,
	op_csgtf_xr,
	op_csgtf_sr,
	op_csgef_rr,
	op_csgef_rd,
	op_csgef_rx,
	op_csgef_rs,
	op_csgef_dr,
	op_csgef_xr,
	op_csgef_sr,
	op_csltf_rr,
	op_csltf_rd,
	op_csltf_rx,
	op_csltf_rs,
	op_csltf_dr,
	op_csltf_xr,
	op_csltf_sr,
	op_cslef_rr,
	op_cslef_rd,
	op_cslef_rx,
	op_cslef_rs,
	op_cslef_dr,
	op_cslef_xr,
	op_cslef_sr,

	// extensions 2005-03-28
	op_pop,
	op_push,

	// extensions 2005-11-12
	op_rtchk_r,
	op_rtchk_d,
	op_rtchk_x,
	op_rtchk_s,

	// extensions 2005-11-25
	op_jsr,

	// extensions 2006-07-01
	op_newctx,
	op_resume_r,
	op_resume_d,
	op_resume_x,
	op_resume_s,
	op_yield,

	// extensions 2006-07-12 "weak references"
    op_wref_rr,
    op_wref_rd,
    op_wref_rx,
    op_wref_rs,
    op_wref_dr,
    op_wref_dd,
    op_wref_dx,
    op_wref_ds,
    op_wref_xr,
    op_wref_xd,
    op_wref_xx,
    op_wref_xs,
    op_wref_sr,
    op_wref_sd,
    op_wref_sx,
    op_wref_ss,

	// extensions 2007-09-13
	op_cmpref_rr,

	// extensions 2008-04-13
	op_newdg,
	op_newdgm,
	op_calldg_r,
	op_calldg_d,
	op_calldg_x,
	op_calldg_s,

	// extensions 2010-02-15
	op_throw,

	// extensions 2014-04
	op_alloci,
	op_calli,
	op_dcvt,

	// extensions 2015-01-01
	op_newdgc,

	// extensions 2015-04-24
	op_jmp,

	JILNumOpcodes
};

#endif	// #ifndef JILOPCODES_H
